### ISSUE TITLE
The Accuracy About CIFAR10

### ISSUE THREAD

**Issue by RandolphCarter0** [cake-lab/datafree-model-extraction#2]
Thank you for sharing you work! I try to run the method in the dataset cifar10 with the file run_cifar_dfme.sh. 
        But the accuracy in cifar10 is 82% at most which is lower than the result 88% in the paper. 
        May I ask you for which measures you take to get the result 88% in the paper? I would appreciate your reply.

**Comment by pratyushmaini** [comment]
Hi! The bash file inadvertently had old parameters, and the new one was pushed last week (in accordance with those in the paper). Thanks for pointing it out.
